name: Run Twitter Bot

on:
  schedule:
    # Runs every 30 minutes from 2:00 AM to 2:00 PM UTC
    - cron: "*/30 2-14 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Run the bot script
      #chnaging the vars ye
      - name: Run the Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python bot.py
